version:  '3.7'
 
services: #объявление блока с описанием сервисов


 javatrack: #микросервис
   environment: #данные бд, а также какой 
     - DATABASE_HOST=db_container
     - DATABASE_USER=${DATABASE_USER}
     - DATABASE_PASSWORD=${DATABASE_PASSWORD}
     - DATABASE_NAME=${DATABASE_NAME}
   container_name: javatrack #имя контейнера
   build: track_ms #указание пути к докерфайлу для сборки
   restart: on-failure #правило перезапуска контейнера
   expose: #открытый порт внутренней сети
     - "8091" 
   depends_on: #сначала должна запуститься бд
     - db_container



 my_nginx: #nginx
   container_name: my_nginx
   image: nginx:latest
   restart: on-failure
   ports:
     - "80:80"
   volumes:
     - ./logs/nginx:/var/log/nginx  #логи
     - ./config/nginx:/etc/nginx/conf.d #конфиги
   depends_on: #сначала должнен запуститься микросервис
     - javatrack
 
 
 
 db_container: #бд
   container_name: db_container
   image: postgres
   restart: on-failure
   expose:
     - "5432"
   environment: #использование переменных окружения
     POSTGRES_USER: ${DATABASE_USER}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
     POSTGRES_DB: ${DATABASE_NAME}
   volumes:
     - ./db:/var/lib/postgresql/data #данные бд
